name: Deploy

on: workflow_dispatch

jobs:
  build:
    name: TEST
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
      - run: |
          git config --file .gitmodules --get-regexp url | while read url; do
            git config --file=.gitmodules $(echo "$url" | sed -E "s/git@github.com:|https:\/\/github.com\//https:\/\/${{ secrets.ALL }}:${{ secrets.ALL }}@github.com\//")
          done
          date > generated.txt
          git submodule update --init --recursive
          git submodule update --remote --merge --recursive
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update submodules"
          git push