name: Deploy

on: workflow_dispatch

jobs:
  build:
    name: TEST
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.CI_TOKEN }}
          submodules: 'true'
      - run: |
          git submodule update --rebase --recursive
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update submodules"
          git push