name: Deploy

on: workflow_dispatch

jobs:
  build:
    name: TEST
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "update of the submodules"
          git submodule update --remote --rebase --recursive